// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDkPC9tl2dHi_DqV-zgOt_liWUZRyefFhE',
//     appId: '1:461587947918:web:cdd3628b96ee2b804584df',
//     messagingSenderId: '461587947918',
//     projectId: 'ocean-cleanup-87642',
//     authDomain: 'ocean-cleanup-87642.firebaseapp.com',
//     storageBucket: 'ocean-cleanup-87642.firebasestorage.app',
//     measurementId: 'G-094N7R6TCR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDPq-uPb2vfHnzNPR2xovnFaiM-850nCVY',
//     appId: '1:461587947918:android:9e3270e9ac7818484584df',
//     messagingSenderId: '461587947918',
//     projectId: 'ocean-cleanup-87642',
//     storageBucket: 'ocean-cleanup-87642.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAMKe7us229jSZEUCXBzSzrkzGlN4vXlTE',
//     appId: '1:461587947918:ios:19cd606bfbae83dc4584df',
//     messagingSenderId: '461587947918',
//     projectId: 'ocean-cleanup-87642',
//     storageBucket: 'ocean-cleanup-87642.firebasestorage.app',
//     iosBundleId: 'com.example.oceanClean',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAMKe7us229jSZEUCXBzSzrkzGlN4vXlTE',
//     appId: '1:461587947918:ios:19cd606bfbae83dc4584df',
//     messagingSenderId: '461587947918',
//     projectId: 'ocean-cleanup-87642',
//     storageBucket: 'ocean-cleanup-87642.firebasestorage.app',
//     iosBundleId: 'com.example.oceanClean',
//   );
// }
